### ISSUE TITLE
Allow formatted body also for MSG.TEXT

### ISSUE THREAD

**Issue by spaetz** [williamkray/maubot-gifme#15]
(UPDATED description after I got a better understanding of the code)
If one sends md formatted messages, !gifme will return the md input format of a message surrounded by blockquote tags. Which is a pity as we lose links, bold text and other formatting when we "save" a normal message. Could we make it possible to also use formatted bodies for TEXT events?

**Comment by spaetz** [comment]
Sorry, having looked at the code closet I have to say, that we never use the formatted_body, we always use the text version. However, when sending out the message, we put the text messaged in a blockquote html tag and "allow_html", which leads to the phenomena, that we get the markdown version of text displayed. So we should either a) store the html version in the database and use that, b) output markdown and set "markdown=True" when sending (in this case we should not put html tags around our post, I guess) b) create an html formatted version when sending and send the formatted_body as content...

**Comment by williamkray** [comment]
fixed with https://github.com/williamkray/maubot-gifme/commit/c0c11d2a5bed3e3ff6cc812583b043f5a2c4e7f5 for me, hopefully for you as well.

saving messages now stores the formatted_body in the database and returns it if it exists, otherwise it will just return the body. so you may want to delete the entries you have and re-save them.

![image](https://user-images.githubusercontent.com/8409433/222046478-2de931a1-cdfd-42a6-8dbb-30068c0028a1.png)

**Comment by spaetz** [comment]
That is great, thank you very much!
