### ISSUE TITLE
Anyone can save NOTICE messages now, even if self.config["allow_non_files"] == False

### ISSUE THREAD

**Issue by spaetz** [williamkray/maubot-gifme#16]
In the case of MessageType.TEXT we verify that "savers" are allowed to save the TEXT, but in the case of NOTICEs, it seems everyone is permitted.

**Comment by williamkray** [comment]
reopening this because the merge that closed it actually broke my bot... shame on me for not testing things first.

i'm also a bit confused, i don't think i've run into this scenario... the bot either uploads an image, or sends a notice. the bot is also disallowed from saving notices, because they generally come from bots (and the idea is that there's no reason to save a bots message, you just do whatever you did before to prompt the same bot to respond).

maybe you're finding a use case i haven't thought of?

**Comment by spaetz** [comment]
To be honest, I have never saved a NOTICE, and apparently I did not understand the code well enough to get that it is not allowed to save any NOTICEs. If that is the case, it is fine with me.

**Comment by spaetz** [comment]
P.S. and sorry for breaking your bot. I had zested this locally for my use and it was fine with that.
